square/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
          path('', views.home, name='homepage'),          
]

square/login/urls.py
from django.urls import path
from . import views

app_name='login'
urlpatterns=[
          path('', views.login_view, name='login'),
          path('logout', views.logout_view, name='logout'),
          path('signup', views.signup_view, name='signup'),
]

square/square/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('booking/', include('booking.urls')),
    path('account/', include('account.urls')),
    path('login/', include('login.urls')),
    path('property/', include('property.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

square/login/models.py
from django.db import models

# Create your models here.

square/login/views.py

from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from account. models import User
from django.contrib.auth.hashers import make_password

def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(email, password)
        
        # Authenticate the user
        user = authenticate(email=email, password=password)
        print(user)
        
        if user is not None:
            # User is authenticated, log them in
            login(request, user)
            # Redirect to the homepage or any other desired page
            return redirect(reverse('home:homepage'))  # Change 'home' to the name of your homepage URL pattern
        else:
            # Authentication failed, display an error message
            error_message = "Invalid username or password. Please try again."
            return render(request, 'login/login.html', {'error_message': error_message})
    else:
        # Display the login form for GET requests
        return render(request, 'login/login.html')
    
def logout_view(request):
    # Log the user out
    logout(request)
    # Redirect to the homepage or any other desired page
    return redirect(reverse('home:homepage'))

def signup_view(request):
    # Handle user signup
    if request.method == 'POST':
        # Create a new user
        if request.POST.get('password') == request.POST.get('confirm_password'):
            user = User()
            user.email = request.POST.get('email')
            user.password = make_password(request.POST.get('password'))
            user.user_type = request.POST.get('user_type')
            user.phone_no = request.POST.get('phone')
            user.name = request.POST.get('name')
            user.gender = request.POST.get('gender')

            if request.FILES.get('profile_pic'):
                pic=request.FILES.get('profile_pic')
                print(pic)
                print(request.FILES.get('profile_pic'))
                user.profile_pic.delete()
                user.profile_pic = pic

                user.username = request.POST.get('username')
                user.save()
                return redirect(reverse('login:login'))
    return render(request, 'login/signup.html')

square/login/templates/login/login.html
<!DOCTYPE <!DOCTYPE html>
<html>
          <head>
                    <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <title>Login</title>
                    <meta name="description" content="">
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <link rel="stylesheet" href="">
                    {% load static %}
                    {% load bootstrap5 %}<!-- loading the bootstrap installed with django-->
                    {% bootstrap_css %}
                    {% bootstrap_javascript %}
          </head>
          <body>
                    <div class='container' style="padding-top: 20vh">
                              <div class='row  gx-5 gy-5'>
                                        <div class='col-md-6'>
                                                  <div class="container">
                                                            <img src="https://cdn.pixabay.com/photo/2023/08/19/10/40/house-8200248_640.jpg" width="100%">
                                                  </div>
                                        </div>
                                        <div class='col-md-6'>
                                                  
                                                  <form action="{% url 'login:login' %}" method="post" style='border:2px solid #4f033d ; border-radius:10px ;padding :3rem; text-align:center '>
                                                            {% csrf_token %}
                                                                      <h1 class='mb-4'>Login</h1>

                                                                      <div class="form-floating mb-3">
                                                                                <input type="email" class="form-control" id="floatingInput" placeholder="Username" name='email'>
                                                                                <label for="floatingInput">Email</label>
                                                                      </div>

                                                                      <div class="form-floating mb-3">
                                                                                <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name='password'>
                                                                                <label for="floatingPassword">Password</label>
                                                                      </div>

                                                                      <div class="mb-3" style='text-align:right;'>
                                                                      <a href="{% url 'login:login' %}" style='color:#4f033d; text-decoration:none;' class='btn'>forget password?</a>
                                                                      </div>
                                                                      
                                                                      
                                                                      <input type="submit" class="btn " style='background-color:#4f033d ; color:#f4f4f4;' value='Login'>
                                                                      <a href="{% url 'login:signup' %}" class="btn " style='background-color:#4f033d ; color:#f4f4f4;'>Signup</a>
                                                  </form>
                                        </div>

                                        
                    
                    <script src="" async defer></script>
          </body>
</html>

square/login/templates/login/signup.html
{% extends 'home/Base.html' %}

{% block content %}
<div class='container'>
          <div class='row  gx-5 gy-5'>
                    <div class='col-md-6'>
                              <div class="container" style="padding-top: 20vh">
                                        <img src="https://cdn.pixabay.com/photo/2024/03/07/10/38/simba-8618301_640.jpg" width="100%">
                              </div>
                    </div>
                    <div class='col-md-6'>
          
          
                    <form method="post" enctype="multipart/form-data">
                                                  {% csrf_token %}
                                                  
                                                  <div class='container mt-5' style=' border:2px solid #4f033d ; border-radius:10px ;padding :3rem; text-align:center '>
                                                            <!-- inline style to css file-->
                                                            <h1 class='mb-4'>signup</h1>

                                                            <div class='mb-3 form-floating'>
                                                                      <input type="text" class="form-control" id="username" name='username' placeholder="username">
                                                                      <label for="username">Usename</label>
                                                            </div>

                                                            <div class="form-floating mb-3">
                                                                      <input type="email" class="form-control" id="floatingInput3" placeholder="name@example.com" name='email'>
                                                                      <label for="floatingInput3">Email address</label>
                                                            </div>

                                                            <div class="form-floating mb-3">
                                                                      <input type="password" class="form-control" id="floatingPassword1" placeholder="Password" name='password'>
                                                                      <label for="floatingPassword1">Password</label>
                                                            </div>

                                                            <div class="form-floating mb-4">
                                                                      <input type="password" class="form-control" id="floatingPassword2" placeholder="Password" name='confirm_password'>
                                                                      <label for="floatingPassword2">Confirm Password</label>
                                                            </div>


                                                            <select name="gender" id="gender" class="form-select mb-4">
                                                                      <option value=1>Male</option>
                                                                      <option value=2>Female</option>
                                                                      <option value=3>Other</option>
                                                            </select>
                                                            <hr>
                                                            <select name='user_type' id='user_type' class="form-select mb-4">
                                                                      <option value=1>Renter</option>
                                                                      <option value=2>Owner</option>
                                                            </select>

                                                            <div class='mb-3 form-floating'>
                                                                      <input type="text" class="form-control" id="name" name='name' placeholder="name">
                                                                      <label for="name">name</label>
                                                            </div>
                                                            <div class='mb-3 form-floating'>
                                                                      <input type="tel" class="form-control" id="phone" name='phone' placeholder="phone">
                                                                      <label for="phone">Phone</label>
                                                            </div>


                                                            <div class="mb-4" style='text-align:left'><!-- inline style to css file-->
                                                                      <label for="formFile" class="form-label">Select Profile image</label>
                                                                      <input class="form-control" type="file" id="formFile" name='profile_pic'>
                                                            </div>
                                                            
                                                            <input type='submit' class="btn btn-outline" value='Signup' style='background-color:#4f033d ; color:#f4f4f4'>
                                                            
                                                  </div>
                                        </form>

                    </div>
          </div>

{% endblock %}