square/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns=[
          path('', views.account, name='profile'),
          path('add_property', views.add_property, name='add_property'),
          path('update', views.edit_profile, name='edit_profile'),
          path('myproperty', views.myproperty, name='myproperty'),
          path('myrental', views.myrental, name='myrental'),
]

square/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
          path('', views.home, name='homepage'),          
]

square/login/urls.py
from django.urls import path
from . import views

app_name='login'
urlpatterns=[
          path('', views.login_view, name='login'),
          path('logout', views.logout_view, name='logout'),
          path('signup', views.signup_view, name='signup'),
]

square/property/urls.py
from . import views
from django.urls import path
app_name = 'property'
urlpatterns=[
          path('<int:property_id>/', views.property_view, name='view'),
          path('remove/<int:property_id>/', views.remove_property, name='remove'),
          
]

square/square/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('booking/', include('booking.urls')),
    path('account/', include('account.urls')),
    path('login/', include('login.urls')),
    path('property/', include('property.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

square/wishlist/urls.py
from django.urls import path
from . import views
app_name = 'wishlist'
urlpatterns=[
          path('', views.wishlist, name='wishlist'),
          path('add_to_wishlist/<int:property_id>/', views.add_to_wishlist, name='add_to_wishlist'),
          
]

square/home/models.py
from django.db import models

# Create your models here.

square/home/views.py
from django.shortcuts import render
from property.models import Property



# Create your views here.
def home(request):

    # need to pass all the retrived infomation from all property individually for easy acees

    all_properties = Property.objects.prefetch_related('propertyimage_set', 'propertylocation_set').all()
    

    # in html code how to render all properties indivialiit reun loop on the context
    # for debuggin purpose

    # context=all_properties try

    # remove the image table and other non necessat table if poasible

    return render(request, 'home/homepage.html', {'properties': all_properties})

square/home/templates/home/Base.html
<!DOCTYPE html>
<html>
          <head>
                    <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <title></title>
                    <meta name="description" content="">
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    {% load static %}
                    {% load bootstrap5 %}<!-- loading the bootstrap installed with django-->
                    {% bootstrap_css %}
                    {% bootstrap_javascript %}
          </head>
          <body class="container" style="width:200vw" >
                    <!--  nav bar  -->
                    <div style="background-color: black; height: 5vh; padding-top: 2vh">
                              {% if user.is_authenticated %}
                                        {% if user.user_type == 2 %}
                                        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding:0px">
                                        <div class="container-fluid" style="background-color:black">
                                                  {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
                                                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                                  <span class="navbar-toggler-icon"></span>
                                                  </button>
                                                  <div class="collapse navbar-collapse row" id="navbarSupportedContent">
                                                            <a class="nav-link active col-2" aria-current="page" href="{% url 'home:homepage' %}">Home</a>
                                                            <a class="nav-link col-2" href="{% url 'wishlist:wishlist' %}">Wishlist</a>
                                                            <a class="nav-link active col-2" aria-current="page" href="{% url 'account:myproperty' %}">My Property</a>
                                                            <a class="nav-link col-2" href="{% url 'account:myrental' %}">My rental</a>
                                                            <a class="nav-link col-2" href="{% url 'account:profile' %}">My Account</a>
                                                            <a class="nav-link col-2" href="{% url 'login:logout' %}">Logout</a>
                                                  </div>
                                        </div>
                                        </nav>
                                        {% else %}
                                        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding:0px">
                                        <div class="container-fluid" style="background-color:black">
                                                  {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
                                                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                                  <span class="navbar-toggler-icon"></span>
                                                  </button>
                                                  <div class="collapse navbar-collapse row" id="navbarSupportedContent">
                                                            <div class ="col-2"></div>
                                                            <a class="nav-link active col-2" aria-current="page" href="{% url 'home:homepage' %}">Home</a>
                                                            <a class="nav-link col-2" href="{% url 'wishlist:wishlist' %}">Wishlist</a>
                                                            <a class="nav-link col-2" href="{% url 'account:myrental' %}">My rental</a>
                                                            <a class="nav-link col-2" href="{% url 'account:profile' %}">My Account</a>
                                                            <a class="nav-link col-2" href="{% url 'login:logout' %}">Logout</a>
                                                  </div>
                                        </div>
                                        </nav>
                                        {% endif %}

                              {% else %}
                              <nav class="navbar navbar-expand-lg navbar-light bg-light"style="background-color:black" >
                                        <div class="container">
                                                  <a class="navbar-brand" href="#" style='width: 10%'>Navbar</a>
                                                  <button class="navbar-toggler"  style="background-color:black"type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                                  <span class="navbar-toggler-icon"></span>
                                                  </button>
                                                  <div class="collapse navbar-collapse row " id="navbarSupportedContent">
                                                                      <p class="col-8"></p>
                                                                      <a class="nav-link active col-2" aria-current="page" href="{% url 'home:homepage' %}">Home</a>
                                                                      <a class="nav-link col-2" href="{% url 'login:login' %}">Login/Register</a>
                                                  </div>
                                        </div>
                              </nav>

                              {% endif %}
                    
                    </div>

                    <hr>

                    {% block hero %}
                    {% endblock %}

                    {% block profile %}
                    {% endblock %}

                    {% block content %}
                    {% endblock %}

                    <hr>

                    {% block properties %}
                    {% endblock %}

                    {% block wishlist %}
                    {% endblock %}

                    {% block booking %}
                    {% endblock %}

                    <hr>

                    {% block script %}
                    {% endblock %}

                    
          </body>
</html>

square/home/templates/home/homepage.html
{% extends 'home/Base.html' %}

{% block hero %}
          <div class="head-img-container">
                    <div class="head_img">
                              <img src="E:\nextsquare\MiniProject\square\square\static\paras\home page\home page\main-page-home1.jpg" alt="">
                    </div>
                    <h2 class="img-text" style="text-align: center">Find Your Perfect Place:
                              <br>
                              Rent with Ease!
                    </h2>
           </div>
{% endblock %}

{% block properties %}
                    <!-- propety elemnt sample  add on hover animation od scale 1.1 transition 2 sec etc-->
            <hr>
                <section class='row gx-5'>
            {% for place in properties %}
        <a class="col-md-4" href="{% url 'property:view' property_id=place.id %}" style='text-decoration:none; color:black;margin-bottom: 20px;'>
                <div class="card" style="border: 1px solid #ccc; border-radius: 5px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); height: 50vh;">
                    {% for image in place.propertyimage_set.all %}
                    <img src="{{ image.default_image.url }}" alt="Property Image" style="height: 200px; object-fit: cover; border-top-left-radius: 5px; border-top-right-radius: 5px;">
                    {% endfor %}
                    <div class="card-body">
                        <h5 class="card-title">{{ place.title }}</h5>
                        <p class="card-text">{{ place.description }}</p>
                        <p class="card-text">Available: {% if place.availabality %} Yes {% else %} No {% endif %}</p>
                        {% for location in place.propertylocation_set.all %}
                                <p>{{ location.location }}</p>
                        {% endfor %}
                        
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
    </section>



          <!-- footer-->
          {% block services %}
                    <div class="container">
                    <hr>
                              <div class="row">
                                        <div class="col-md-4">
                                                  <img src="E:\nextsquare\MiniProject\square\square\static\paras\home page\home page\home logo.png" alt="">
                                                  <h4>Enjoy Some Flexibility</h4>
                                                  <h6>make it easy to book your space </h6>
                                        </div>

                                        <div class="col-md-4">
                                                  <img src="E:\nextsquare\MiniProject\square\square\static\paras\home page\home page\headphone.png" alt="">
                                                  <h4>24/7 CUSTOMER SERVICE</h4>
                                                  <h6>Friendly 24/7 customer support </h6>
                                        </div>

                                        <div class="col-md-4">
                                                  <img src="E:\nextsquare\MiniProject\square\square\static\paras\home page\home page\Icon-check.png" alt="">
                                                  <h4>MONEY BACK GUARANTEE</h4>
                                                  <h6>We reurn money within 30 days </h6>
                                        </div>
                              </div>
                    </div>
                    {% endblock %}

                    <footer style="background-color: black; padding-bottom: 5vh; color:white">
                              <hr>
                              <div class="row g-2">
                                        <div class="col-md-4">
                                        <h3>Support</h3>
                                        <ul>
                                                  <li>Contact us</li>
                                                  <li>Cancellation support</li>
                                                  <li>Report a problem</li>
                                        </ul>
                                        </div>

                                        <div class="col-md-4">
                                        <h3>Account</h3>
                                        <ul>
                                                  <li><a href="#">My Account</a></li>
                                                  <li><a href="#">Login/Register</a></li>
                                                  <li><a href="#">Wishlist</a></li>
                                        </ul>
                                        </div>

                                        <div class="col-md-4">
                                        <h3>About nextsquare</h3>
                                        <p class="about_P">We provide rental solutions for homes, garages, and warehouses, ensuring convenience and satisfaction
                                                  for both
                                                  tenants and property owners with our curated selection of properties and streamlined processes.</p>
                                        </div>
                              </div>
                    </footer>


{% endblock %}