square/booking/urls.py
from django.urls import path
from . import views

app_name='booking'
urlpatterns=[
          path('', views.booking, name='booking'),
          path('history/', views.history, name='history'),
          path('cancalation/<int:booking_id>/', views.cancle, name='cancle'),
          
]

square/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
          path('', views.home, name='homepage'),          
]

square/property/urls.py
from . import views
from django.urls import path
app_name = 'property'
urlpatterns=[
          path('<int:property_id>/', views.property_view, name='view'),
          path('remove/<int:property_id>/', views.remove_property, name='remove'),
          
]

square/square/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('booking/', include('booking.urls')),
    path('account/', include('account.urls')),
    path('login/', include('login.urls')),
    path('property/', include('property.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

square/wishlist/urls.py
from django.urls import path
from . import views
app_name = 'wishlist'
urlpatterns=[
          path('', views.wishlist, name='wishlist'),
          path('add_to_wishlist/<int:property_id>/', views.add_to_wishlist, name='add_to_wishlist'),
          
]

square/property/models.py
from django.db import models

# Create your models here.
class Property(models.Model):
          title = models.CharField(max_length=100,null=True,blank=True)
          description = models.TextField(null=True,blank=True)
          times_rented=models.IntegerField(default=0)
          availabality=models.BooleanField(default=True)

          # some property owners prefer that they rent only for particular age group, for example they prefer to rent only for students, for girls, etc
          Choices=((1,'Family'),(2,'Bachelor'),(3,'Students'),(4,'Only_for_Girls'),(5,'Only_for_Boys'),(6,'all'))
          user_preference=models.IntegerField(choices=Choices,default=6)

          owner=models.ForeignKey('account.User',on_delete=models.CASCADE)

          # write __str__ methos for all class such that deleting dont contradict

          

class propertyImage(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    default_image = models.ImageField(upload_to='media/property_images')
    image2 = models.ImageField(upload_to='media/property_images', null=True, blank=True)
    image3 = models.ImageField(upload_to='media/property_images', null=True, blank=True)
    image4 = models.ImageField(upload_to='media/property_images', null=True, blank=True)
    image5 = models.ImageField(upload_to='media/property_images', null=True, blank=True)

    

    
class propertyVideo(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    default_video = models.FileField(upload_to='media/property_videos')
    video2 = models.FileField(upload_to='media/property_videos', null=True, blank=True)


    



class typeOfProperty(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    Choices=((1,'Residential'),(2,'Commercial'),(3,'Storts Ground'),(4,'Apartment'),(5,'Villa'),
             (6,'Office'),(7,'Shop'),(8,'Warehouse'),(9,'Factory'),(10,'Hotel'),
             (11,'Cottage'),(12,'Farmhouse'),(13,'Cabin'),(14,'Penthouse'),(15,'Swimming Pool'),
             (16,'Clubhouse'),(17,'Garden'),(18,'Gym'),(19,'Cinema'),(20,'Cafe'),
             (21,'Stadium'),(22,'Room')
             )
    property_type = models.IntegerField(choices=Choices,default=1)
    



    

class propertyLocation(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    location = models.CharField(max_length=100,null=True,blank=True)
    city=models.CharField(max_length=100,default='')
    state=models.CharField(max_length=100,default='')
    country=models.CharField(max_length=100,default='')
    zipcode=models.CharField(max_length=6,default='')


    
class pricing(models.Model):
    Choices=((1,'PerDay'),(2,'PerWeek'),(3,'Monthly'),(4,'Yearly'))
    property = models.ForeignKey(typeOfProperty, on_delete=models.CASCADE)
    price_type = models.IntegerField(choices=Choices,default=1)
    price = models.FloatField( default=0)




class currentrenter(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey('account.User', on_delete=models.CASCADE)

    


square/property/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Property, propertyImage, typeOfProperty, propertyLocation, currentrenter,pricing
from reviews.models import reviews, rating 
from booking.models import Booking, Transaction
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

#  .filter method gives back query set

#  .get method gives back obkject

#  returns property,imah=ge, type object
def get_property_display(property_id):
    try:
        property_ = Property.objects.get(pk=property_id)
        print(property_)
        print()
        
        image_=propertyImage.objects.get(property=property_)
        print(image_)
        print()

        type_=typeOfProperty.objects.get(property=property_)
        print(type_)
        print()

        location_ = propertyLocation.objects.get(property=property_)

        return {
            'property': property_,
            'image': image_,
            'type': type_,
        }
    
    except Property.DoesNotExist:
        return None


# returns revies and rating of property
def get_reviews(property_id):
    property_=Property.objects.get(pk=property_id)
    reviews_ = reviews.objects.filter(property=property_)
    print(reviews_)
    #print()

    # Retrieve ratings for the property
    ratings_ =  rating.objects.filter(property=property_)
    print(ratings_)
    #print()
        
    return {
        'reviews': reviews_,
        'ratings': ratings_,
        }





def property_view(request, property_id):
    """
    View function to render the property detail page.
    """
    # Retrieve property info using the provided property_id
    place=get_property_display(property_id)
    print(place)
    reviews=get_reviews(property_id)
    print(reviews)

    if property:
        # If property info is found, render the detail page

         # property detials to be fetched like pricing, location etc
        return render(request, 'property/property.html', {'place': place, 'data': reviews})
    else:
        # If property info is not found, render a 404 page
        return render(request, '404.html', status=404)



def remove_property(request, property_id):  # Add property_id parameter
    if request.method == 'POST':
        print(property_id)
        property = Property.objects.get(id=property_id)
        print(property)
        if property.availabality == False:
            messages.error(request, 'Cannot delete property with active booking')
            print('Cannot delete property with active booking')
            return redirect(reverse('property:view',kwargs={'property_id': property_id}))  # Redirect to the user's profile page
        property.delete()
        print('deleted')
        return redirect(reverse('account:myproperty'))  # Redirect to the user's profile page
    return redirect(reverse('property:view',kwargs={'property_id': property_id}))  # Return a response for other HTTP methods

square/property/templates/property/property.html
{% extends 'home/base.html' %}

{% block properties %}
    
    {% if messages %}
        <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}


<div class='container' style="height: 80vh">
    <div class='container'>
        <img src="{{ place.image.default_image.url }}" class="img-fluid" alt="hero image"  style="height: 60vh ;padding-left: 15vw;padding-right: 15vw">
        <hr>
    </div>
    {% if user.is_authenticated%}
    <a href="{% url 'wishlist:add_to_wishlist' place.property.id  %}" style='position:fixed; bottom:5vh; right:10vw; '><button type="button" class="btn btn-dark" id='add_payment' style=" background-color:#4f033d ; color:#f4f4f4;margin-bottom:20px" >Wishlist</button></a>
    {% endif %}
    <div class='container'>
        <div class='row gy-3 gx-3'style='height: 20vh; padding-left: 5vw;padding-right: 5vw'>
                <div class='col-2'>
                <img src="{{ place.image.default_image.url }}" class="img-fluid" alt="default_image" style="height: 12vh">
                </div>
                <div class='col-2'>
                <img src="{{ place.image.image2.url }}" class="img-fluid" alt="default_image" style="height: 12vh">
                </div>
                <div class='col-2'>     
                <img src="{{ place.image.image3.url }}" class="img-fluid" alt="default_image" style="height: 12vh">
                </div>
                <div class='col-2'>
                <img src="{{ place.image.image4.url }}" class="img-fluid" alt="default_image" style="height: 12vh">
                </div>
                <div class='col-2'>
                <img src="{{ place.image.image5.url }}" class="img-fluid" alt="default_image" style="height: 12vh">
                </div>
            <hr>
        </div>
    </div>
</div>

<div class='container' style="background-color: #f9f9f9; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    <h3 style="color: #333; font-size: 24px; margin-bottom: 10px;">Title: {{ place.property.title }}</h3>
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">Description: {{ place.property.description }}</p>
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">No of Times Rented: {{ place.property.times_rented }}</p>
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">Owner: {{ place.property.owner }}</p>
    {% if place.property.availabality %}
    <p style="color: #3cb371; font-size: 16px; margin-bottom: 5px;">Available</p>
    {% else %}
    <p style="color: #ff6347; font-size: 16px; margin-bottom: 5px;">Not Available</p>
    {% endif %}
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">State: {{ place.property.location.state }}</p>
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">Country: {{ place.property.location.country }}</p>
    <p style="color: #333; font-size: 18px; margin-bottom: 5px;">Price: {{ place.type.pricing_set.first.price }}</p>
    <p style="color: #666; font-size: 16px; margin-bottom: 5px;">Price Type: {{ place.type.pricing_set.first.get_price_type_display }}</p>
    {% if user.user_type == 2%}
        <form method="post" action="{% url 'property:remove' property_id=place.property.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark" style="background-color:#4f033d; color:#f4f4f4; margin-bottom:20px;">Remove</button>
        </form>
     {% endif %}
</div>

<hr>

<div class='container' style="background-color: #f9f9f9; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    <!-- Booking Section -->
    <form action="{% url 'booking:booking' %}" method="POST" id="booking_form" style="margin-bottom: 20px;">
        {% csrf_token %}
        <label for="start_date" style="font-weight: bold; margin-bottom: 5px;">Start Date:</label>
        <input type="date" name="start_date" id="start_date" required style="padding: 8px; border-radius: 5px; border: 1px solid #ccc; margin-bottom: 10px;">
        <br>
        <label for="end_date" style="font-weight: bold; margin-bottom: 5px;">End Date:</label>
        <input type="date" name="end_date" id="end_date" required style="padding: 8px; border-radius: 5px; border: 1px solid #ccc; margin-bottom: 10px;">
        <br>
        <button type="button" id="calculate_button" style="background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Calculate</button>
        <p id="result" name="amount" style="font-size: 16px; margin-top: 10px;"></p> <!-- Change the id to result -->
        <input type="hidden" name="amount" id="amount"> <!-- Add a hidden input field for amount -->
        <br>
        <input type="hidden" name="property" id="property" value="{{ place.property.id }}"> 
        <input type="submit" value="Confirm Booking" style="background-color: #008CBA; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
    </form>
</div>


<!-- Reviews Section                     working still need to add upade and remive options 
<div class='container'>
    <h3>Reviews</h3>
    {% for review in data.reviews %}
        <p> {{ review.user.username }}: {{ review.review }} </p>
    {% empty %}
        <p>No reviews available</p>
    {% endfor %}
</div>
-->



<script>
    document.getElementById('calculate_button').addEventListener('click', function(event) {
        event.preventDefault(); // Prevent the form from submitting

        // Get the start date and end date values
        var startDate = new Date(document.getElementById('start_date').value);
        var endDate = new Date(document.getElementById('end_date').value);

        // Get the price and price type from Django template variables
        var price = {{ place.type.pricing_set.first.price }};
        var priceType = {{ place.type.pricing_set.first.price_type }};

        // Calculate the difference in days between start date and end date
        var differenceInDays = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24));

        // Calculate the amount based on the price type
        var amount;
        if (priceType === 1) {
            amount = differenceInDays * price;
        } else if (priceType === 2) {
            amount = Math.ceil(differenceInDays / 7) * price;
        } else if (priceType === 3) {
            amount = Math.ceil(differenceInDays / 30) * price;
        } else if (priceType === 4) {
            amount = Math.ceil(differenceInDays / 365) * price;
        }

        // Set the calculated amount in the result paragraph and hidden input field
        document.getElementById('result').textContent = "Amount: " + amount.toFixed(2); // Display amount
        document.getElementById('amount').value = parseInt(amount.toFixed(2)); // Set amount in hidden input
    });
</script>


{% endblock %}

<!--   update  the data of the property like time srented staus etc.
        add review feature
-->